Repository ahm-monash/evergreen, pull requests merged in 2022-11, with the labels that each got.

#267 Customizable Icon Colors and Polishing UI
  components/MobileComponents/MobileGridComponents/GridRow.tsx
  components/ReposTableComponents/CollapsibleTable.tsx
  components/ReposTableComponents/DependenciesContainer.tsx
  components/ReposTableComponents/Tabs.tsx
  components/icons/IconFactory.tsx
  components/icons/StatusIcon.tsx
  components/images/greenLight.svg
  components/images/redLight.svg
  components/images/yellowLight.svg
  global.css
  next.config.js
  package-lock.json
  package.json
  styles/CollapsibleTable.module.css
Labels: enhancement

#284 Fixed CSS bug for Help Guide
  components/HelpComponents/HelpGuide.tsx
  styles/HelpGuide.module.css
Labels: bug, enhancement

#286 Fixing text overflow and sign in card/buttons CSS bugs
  global.css
  pages/signin.tsx
  styles/SummaryContainer.module.css
  styles/signin.module.css
Labels: bug, enhancement

#290 Applied sorting for internal tables
  components/Page.tsx
  components/ReposTableComponents/SortAndFilterDropdowns.tsx
  src/sortingAndFiltering.ts
Labels: enhancement

#292 Add chips for selected dependency filter
  components/Page.tsx
  components/ReposTableComponents/DependenciesContainer.tsx
  components/SummaryComponents/ReposSecondarySummaryTable.tsx
Labels: enhancement

#272 updated readme
  README.md
Labels: documentation

#295 Fixed status legend background
  components/MobileComponents/MobileSummaryContainer.tsx
  styles/LightStatus.module.css
Labels: bug

#273 Revert "Added ssh support for azure web app container (#260)"
  Dockerfile
  run.sh
  ssh_setup.sh
  sshd_config
Labels: DO NOT MERGE

#306 Alex/testing
  tests/README.md
  tests/collapsibletable.test.tsx
  tests/k6/README.md
  tests/parameters.test.ts
  tests/semVer.test.ts
Labels: enhancement

#308 Added missing overall description for mobile view
  components/MobileComponents/MobileSummaryContainer.tsx
  components/SummaryComponents/SummaryContainer.tsx
Labels: bug

#309 Removed status legend for mobile view summary
  components/MobileComponents/MobileSummaryContainer.tsx
Labels: bug
